kong/types.go

Fixes a copy-paste error in a docstring for `type Upstream`.

docs: Upstream docstring: fix a copy-paste error

---

kong/consumer_service.go
kong/error.go
kong/error_test.go
kong/kong_test.go
kong/response.go
kong/response_test.go

This PR:
- improves error messages returned by HTTP calls to Kong Admin API by including the `message` from the response body,
- ensures that all users test errors for being equal to 404 by means of the public API.
Inspired by https://github.com/Kong/deck/issues/218#issuecomment-712192401.

feat: rich HTTP errors

---

kong/consumer_service.go
kong/error.go
kong/error_test.go
kong/response.go
kong/response_test.go

Exports KongAPIError and a method `Code` is added to it which returns the HTTP status code
Closes #10

feat: export KongAPIError and expose HTTP status code

---

CHANGELOG.md
kong/types.go
kong/zz_generated.deepcopy.go

`Service.URL` is a prerequisite for https://github.com/Kong/kubernetes-ingress-controller/issues/925. The `v0.16.0` release aims at adding the `URL` field.
Also, v0.15.0 was released without a changelog. This PR fixes that.

Release v0.16.0. Add Service.URL. Add changelog for v0.15.0.

---

go.sum
kong/acl_service.go
kong/admin_service.go
kong/basic_auth_service.go
kong/ca_certificate_service.go
kong/certificate_service.go
kong/consumer_service.go
kong/credentials_service.go
kong/custom_entity_service.go
kong/endpoint_permission_service.go
kong/entity_permission_service.go
kong/error.go
kong/error_test.go
kong/hmac_auth_service.go
kong/jwt_auth_service.go
kong/key_auth_service.go
kong/kong.go
kong/mtls_auth_service.go
kong/oauth2_auth_service.go
kong/plugin_service.go
kong/rbac_role_service.go
kong/rbac_user_service.go
kong/response.go
kong/route_service.go
kong/service_service.go
kong/sni_service.go
kong/target_service.go
kong/upstream_node_health_service.go
kong/upstream_service.go
kong/workspace_service.go

Add interface types for the various Kong endpoint services and a function to generate Kong API errors. This allows code using this library to define mock types that implement the service without interacting with a Kong instance and instead return canned responses for unit tests.
For example usage, see the WIP branches at
https://github.com/Kong/kubernetes-ingress-controller/tree/refactor/validator-mocking
https://github.com/Kong/kubernetes-ingress-controller/tree/refactor/validator-mocking-plugin

Add interface types for all go-kong services

---

.ci/setup_kong.sh
kong/admin_service_test.go
kong/developer_role_service.go
kong/developer_role_service_test.go
kong/endpoint_permission_service_test.go
kong/entity_permission_service_test.go
kong/kong_test.go
kong/rbac_role_service.go
kong/rbac_role_service_test.go
kong/rbac_user_service_test.go
kong/workspace_service_test.go

Carried on from #29. Includes the original change from that and changes to require the Portal for Portal feature tests, as it is not set up by default, and further requires admin API requests to make it available on a workspace.
Removes the RBAC requirement from Portal tests, since they don't actually require RBAC. The original merge from #26 passed CI once in main, which suggests there's maybe something going wrong with CI RBAC setup--while my local test environment didn't have RBAC on and the tests did not run at all, it looks like RBAC-only tests [should run in CI](https://github.com/Kong/go-kong/blob/v0.16.0/.ci/setup_kong.sh#L45), so the Portal tests should have failed earlier.
See https://github.com/Kong/go-kong/pull/29#issuecomment-807396216 for a bit more background.

Add DevRole/RBAC pagination and ListAll; require the Portal for Portal tests

---

kong/endpoint_permission_service_test.go
kong/entity_permission_service_test.go
kong/types.go

The custom JSON marshalers for these types omitted the Negative field, which prevented decK (or any other user of go-kong) from applying it. This was originally reported internally in FTI-2405. To recap/demonstrate, repeated syncs of [negative.yaml.txt](https://github.com/Kong/go-kong/files/6232800/negative.yaml.txt) would not never actually sync a negative permission, since the PATCH omitted that field:
```
./deck sync -s negative.yaml --rbac-resources-only --verbose 2
{"next":null,"data":[{"endpoint":"\/acls","created_at":1617146918,"workspace":"default","actions":["delete","create","update","read"],"negative":false,"comment":null,"role":{"id":"bb1522dc-e323-456a-bb9d-1d5f3fd07f6d"}}]}
updating rbac-endpointpermission bb1522dc-e323-456a-bb9d-1d5f3fd07f6d-default-/acls  {
"actions": …
```

fix(rbac) include Negative when marshaling RBAC

---

kong/utils.go

This cosmetic change make it easier
for the caller to use the API.

refactor: return a pointer to client

---

.ci/setup_kong.sh
.github/workflows/test.yaml

Updates version lists and package locations to make CI work with our new package repository. Our repository has some structural differences from Bintray, and the new version gates in setup_kong.sh account for this.
Test runs (with some additional diagnostic modifications) can be seen on https://github.com/rainest/go-kong/pull/6
1.3.0.2 Enterprise will still fail with this change. Our current credentials are for Bintray, not download.konghq.com. However, download.konghq.com also uses basic auth, so I don't expect we'll need changes to the script, only to the repo secret.

Update CI package locations and test versions

---

kong/client.go
kong/exists.go
kong/tag_service.go
kong/tag_service_test.go
kong/workspace_service.go
kong/workspace_service_test.go

This is to use a service instead of 
https://github.com/Kong/kubernetes-ingress-controller/blob/fa0afebe1ccd19551305c89008d829a10790a1a0/cli/ingress-controller/main.go#L293-L296
And
https://github.com/Kong/kubernetes-ingress-controller/blob/ed88ebee538681888f303c572c139410f4d686f8/cli/ingress-controller/util.go#L35-L42
The logic of HEAD testing shall be moved somewhere to be reuse but I don't see where for now

Check existence of tags or a workspace with the HEAD http verb instead of GET

---

kong/client.go

Go's default client has no timeouts and relies on the kernel timeouts,
which goes against the recommended practice of setting timeouts at
application-level whenever possible.
This change ensures that if the default client is used, it is used with
proper timeouts for TCP handshake, TLS handshake and HTTP
request-response lifecycle.
There is no emperical data for the value of 10 seconds.
It is a good starting point and a sane default. Users are encouraged to
create their own http.Client and many users already do so to control
TLSConfig.

feat: add timeouts when default client is in use

---

.github/workflows/test.yaml

1.x series is no longer supported and maintained by Kong Inc so removing
testing against those.
See #47

chore(ci) drop testing against older versions of Kong

---

kong/client.go
kong/request.go

Fixes https://github.com/Kong/go-kong/pull/48#issuecomment-840122457

Handle workspace in Kong's client

---

CHANGELOG.md

release `v0.20.0`, needed soon by KIC for the relevant workspace fixes.

chore: update CHANGELOG for v0.20.0

---

kong/credentials.go
kong/zz_generated.deepcopy.go

Adds the [newish oauth2 `hash_secret` field](https://github.com/Kong/kong/blame/6455987f64f99aa40ca3ddf415915b6d48683344/kong/plugins/oauth2/daos.lua#L36) to the matching go-kong schema.
Requested in https://github.com/Kong/kubernetes-ingress-controller/issues/1521 but the change needs to go here.
Been a while since I've added a new field to some existing struct, so to confirm, we don't need related changes downstream, correct? Adding the field here and bumping to a new go-kong version with it is all decK and KIC need to start using the field, correct?

feat: add oauth2 hash_secret field

---

go.mod
go.sum
kong/acl_service_test.go
kong/basic_auth_service_test.go
kong/ca_certificate_service_test.go
kong/certificate_service_test.go
kong/consumer_service_test.go
kong/developer_role_service_test.go
kong/developer_service_test.go
kong/hmac_auth_service_test.go
kong/jwt_auth_service_test.go
kong/key_auth_service_test.go
kong/mtls_auth_service_test.go
kong/oauth2_auth_service_test.go
kong/plugin_service_test.go
kong/rbac_role_service_test.go
kong/route_service_test.go
kong/service_service_test.go
kong/sni_service_test.go
kong/target_service_test.go
kong/upstream_service_test.go
kong/workspace_service_test.go

This PR is for avoiding to have several dependencies responsible for the uuid handling. It will reduce the number of dependencies in deck and kic and ktf

Use github.com/google/uuid instead of github.com/satori/go.uuid

---

kong/plugin_service.go
kong/plugin_service_test.go

Add a new string return value to PluginService.Validate(). When the
response is a validation failure, this string is the response body
message and the error is nil. Actual errors (e.g. connection timeouts,
response parse failures, etc.) still set the error.
Previously, failures also set the error. Downstream applications were
unable to determine whether the validation attempt was unsuccessful or
if the validation attempt was successful and confirmed the payload was
invalid.
This is a breaking API change for anything that uses Validate(). Not sure if that's anything other than the controller yet.

feat(plugin) separate validation errors and fails

---

go.mod
go.sum
kong/client.go
kong/client_test.go
kong/listeners.go
kong/listeners_test.go

This patch adds the ability to retrieve the `proxy_listeners` and `stream_listeners` from the data-plane as convenient Go types.
The original use case for this is to make it easy to retrieve L7 information about Kong listeners for the upcoming Gateway APIs support in KIC.
This focuses on a minimal, but forward thinking implementation: we could take this further from where this leaves off and make the kong root a full object (and this leaves us in a fine place to do that next) but that wasn't the immediate need.

feat: root listeners methods

---

kong/types.go

Add kubebuilder validation annotation comments to healthcheck-related types. This allows generating schema validation for fields within them in Kubebuilder-generated CRDs. See https://github.com/Kong/kubernetes-ingress-controller/pull/1971#discussion_r763391075

feat(types) add kubebuilder to health types

---

CHANGELOG.md

Well, I stand corrected re https://github.com/Kong/go-kong/pull/107#issuecomment-989166927
While nothing was using the original 0.25.0 release, Github apparently has it... somewhere, as `go get` refuses to pull the revised version, even on a machine that hadn't pulled the original the past.

doc(changelog) add 0.25.1

---

go.mod
go.sum
kong/plugin_service.go
kong/plugin_service_test.go
kong/utils.go

`GetFullSchema`: returns full schema for plugins (`/schemas/plugins/<ID>`)
`FillDefaults`: given a schema and a config object, fills all defaults
Based on the discussion happening in [here](https://github.com/Kong/deck/pull/562), this PR is introducing 2 new methods for `Plugin` (along few other helper functions, mostly taken from [KIC](https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/deckgen/deckgen.go#L121-L122) plus few changes).
These can be leveraged by `deck` and `KIC` to fill defaults values into plugins from their schemas.

feat: add GetFullSchema and FillDefaults methods to plugins

---

CHANGELOG.md

Release for changes needed by `deck` [here](https://github.com/Kong/deck/pull/562) and [here](https://github.com/Kong/deck/pull/573).

doc(changelog): release 0.26.0

---

go.mod
go.sum
kong/utils.go
kong/utils_test.go

We recently forked and patched `mergo` (https://github.com/Kong/mergo/pull/1)
to improve the way we can handle zero-value fields with defaults values.
Currently, if an entity field is set with a zero-value (e.g. a target
with weight=0, a route with strip_path=false etc.), we will overwrite it
when merging it with its default if this is not a zero-value itself.
This updates the `mergo` dependence and adds a custom transformer to support
such cases as well. Also, add few test cases with zero-value fields.

feat: improve handling zero-value fields with defaults

---

kong/utils.go
kong/utils_test.go

Change the Enterprise suffixes from semver pre-releases to semver build info, so that Enterprise tests against the initial minor release do run as expected.

feat(utils) make Enterprise info build info

---

kong/types.go

As highlighted in https://github.com/Kong/deck/issues/586, `go-kong` renders RBAC permissions as a comma-separated string..
```
rbac_roles:
- comment: Full access to all endpoints, across all workspaces
endpoint_permissions:
- actions: delete,create,read,update
```
...instead of an actual array:
```
rbac_roles:
- comment: Full access to all endpoints, across all workspaces
endpoint_permissions:
- actions:
- update
- create
- delete
- read
```
With this, `deck` is happy:
```
$ deck dump --rbac-resources-only -o permissions.yaml
$ deck sync --rbac-resources-only -s permissions.yaml
Summary:
Created: 0
Updated: 0
Deleted: 0
```

fix: correctly marshal RBAC 'actions'

---

kong/admin_service_test.go
kong/client_test.go
kong/developer_role_service_test.go
kong/developer_service_test.go
kong/endpoint_permission_service_test.go
kong/entity_permission_service_test.go
kong/rbac_role_service_test.go
kong/rbac_user_service_test.go
kong/test_utils.go
kong/workspace_service_test.go

Recently we exported the RunWhenKong and RunWhenEnterprise utils,
but the latter is not usable if we don't export requiredFeatures too.

tests: export requiredFeatures

---

kong/plugin_service.go

Fix the issue #137 
Before checking the HTTP Status Code from response, we need to make sure the response is not nil. So, if the response is nil, then we return the fail validation of plugin, an empty message and the error.

fix: nil pointer deference on plugin validate

---

kong/plugin_service_test.go
kong/utils.go

A few issues ([here](https://github.com/Kong/deck/issues/612) and [here](https://github.com/Kong/deck/issues/610)) have been opened
on decK that suggest we sometimes parse wrongly the plugins defaults
coming from their schema, merging into the config object fields
that are not part of the config schema itself.
This makes sure that we only merge together the right attributes.

fix: only fills defaults for plugins config schemas

---

kong/client.go

Adds support for the configuration hash added to 2.8's status endpoint.

feat(client) add configuration_hash to Status

---

CHANGELOG.md

Release 0.29.0, tentatively today, 2022-03-25. Needs a date bump if we don't have time to approve today.

doc(changelog) release 0.29.0

---

.github/workflows/golangci-lint.yml
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml

This PR limits the events on which the CI actions will run in order to run them only once (for `pull_request` event, not for `push` event).
For now the `push` trigger will only run actions on `main` and `release/*` branches.
---
Do we want to trigger CI checks on release branches? Do we want to run them on any other branches?

ci: run CI checks only for PRs and selected branches

---

.github/workflows/kong-license.yaml

This adds a Github Actions' cron which will try to update the secret with Kong license (named: `KONG_LICENSE_DATA`) by pulling it from Pulp.
Apart from pulp related secrets (that contain credentials and the URL) this workflow requires [Github Personal Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with `repo` permissions.

ci: add Github Actions' cron to update Kong license

---

kong/client_test.go
kong/custom_entity_service.go
kong/utils.go
kong/utils_test.go

When caller uses
```go
kong.NewClient(<URL>, kong.HTTPClientWithHeaders(&http.Client{}, <HEADERS>))
```
where the `http.Client`'s transport is uninitialized then issuing a request will cause a panic.
This PR addresses that by setting the transport to `http.DefaultTransport` whenever the caller provided the client but didn't set the transport.

fix: set default transport when caller provides uninitialized one

---

.github/workflows/kong-license.yaml

In order to help in debugging with missing license CI errors, let's relax Github workflow masks to show some parts of the license so that it's easier to figure out if the license indeed is outdated (or missing).
Exemplar CI workflow: https://github.com/pmalek/go-kong/runs/7128060127?check_suite_focus=true#step:3:4
Exemplar logs:
```
Run gliech/create-github-secret-action@ea87807ab20663b30a1a2d14d7f6dd9490b1e7a1
with:
name: KONG_LICENSE_DATA
value: {"license":{"payload":{"***_seats":"5","customer":"automation","dataplanes":"100","license_creation_date":"2022-06-10","license_expiration_date":"2022-07-20","license_key":***,"product_subscription":"Konnect Enterprise","support_plan":"None"},"signature":"e3923b0e7f***","version":"1"}}
pa_token: ***
org_visibility: private
```
Related CI …

chore(ci): relax github workflow masks to ease license debugging

---

.github/workflows/integration-test.yaml

The OSS tests do not need a license, and the environment variable's [original presence in them](https://github.com/Kong/go-kong/commit/fd79bea198187eb794fa89428d3cb3149040daf2#diff-b6766eb8febc0c51651250cd0cdfb44c4f0d3256470d88e62bf82fd46aa73ae0L30) was probably an unnecessary copy-paste. Unfortunately the old variable would be benignly empty for the tests that didn't need it, whereas the new job will actually fail them :fearful:

fix: remove license from OSS CI

---

go.mod
go.sum
kong/types.go
kong/zz_generated.deepcopy.go

add the 4 new fields in `Upstream`:
- `hash_on_query_arg`
- `hash_fallback_query_arg`
- `hash_on_uri_capture`
- `hash_fallback_uri_capture`
would fix #199.

feat: add new fields in upstreams of kong 3.0

---

CHANGELOG.md

I was real smart and forgot to actually create the previous release after merging a PR for it, and forgot to put in a proper date to boot.
So this PR is releasing 0.31 even harder than last time, with assurances that I will actually remember to create the release after this time.

chore: release 0.31

---

CHANGELOG.md
kong/plugin_service.go
kong/plugin_service_test.go

Small fix for the PR : https://github.com/Kong/go-kong/pull/192
It seems that we let a small error within the PR, the PluginID was mandatory, sorry.

fix - let the PluginId be optional like the create method.

---

go.mod
go.sum
kong/plugin_service_test.go
kong/test_utils.go
kong/utils.go
kong/utils_test.go
kong/versioning.go
kong/versioning_test.go

This feature adds four digit versioning for Kong Gateway; OSS and enterprise. Starting with 3.0.0.0 Kong Gateway has dropped the "enterprise-edition" suffix from the version in both the CLI output and the version field from the root endpoint. Moving forward all four digit versions and any version ending with the "enterprise" or "enterprise-edition" suffix will be considered an enterprise edition.
This feature also allows for updated version range comparisons to use the fourth digit. This is beneficial when comparing against revision updates for Kong Gateway allowing for more granular specifications.
Note: This feature also removes pre-release and build metadata information from the underlying kong/semver implementation so that any pre-release can be compared to an actual version number.

feat: add support for Kong Gateway four digit versioning

---

.ci/setup_kong.sh
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml
CHANGELOG.md
kong/client_test.go
kong/plugin_service_test.go
kong/target_service_test.go

Adds 0.32 changelog and updates test matrices.
This will probably fail initially because 3.0 is still wonky on Docker and can't run on linux/amd64 (or, for that matter, anything) yet.
1.5.0.11 gained a [failure in the plugin service](https://github.com/Kong/go-kong/actions/runs/3048010392/jobs/4912614044) at some point. As it [exited support in April](https://docs.konghq.com/gateway/latest/support-policy/#version-support-for-kong-gateway-enterprise), I think we should just go ahead and remove it from the tests.
This skips several tests that are incompatible with 3.x:
- The target health setters use POST as was required by 2.x. 3.x requires PUT, and there's not an existing pattern that allows us to choose the method (or anything else) in service functions based on the Kong version. …

Release 0.32

---

CHANGELOG.md

This PR fixes the changelog with proper link for v0.32.0 and adds new entries from PRs that were merged.

chore: update CHANGELOG.md for v0.32.0

---

CHANGELOG.md
kong/testdata/routeJSONSchema.json
kong/testdata/serviceJSONSchema.json
kong/testdata/targetJSONSchema.json
kong/testdata/upstreamJSONSchema.json
kong/utils.go
kong/utils_test.go

FillEntityDefaults can be used to inject Kong entity defaults into a Kong entity struct. This function achieves this by getting entity schemas from the Admin API, flattening the returned schemas and merging these with the input schemas.
Kong CP only works with Lua schemas, while Konnect also supports JSON schemas.
This commit adds support to filling entity defaults from JSON schemas.

feat: support JSON schemas in the FillEntityDefaults function

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
kong/admin_service.go
kong/rbac_user_service.go
kong/utils.go

This PR unpins `v1.48.0` `golangci-lint` version and adds more rules to its config. It also makes sure that files with build tag `enterprise` are also checked with the linter.

ci: unlock CI golangci-lint version and add more rules

---

kong/plugin_service_test.go
kong/utils.go

The current implementation of the `fillConfigRecord` function works as follows:
- navigate the entity structure
- for each field, check whether it's set or not
- if it's already set, move onto the next field
- if it's not set, check the entity schema and set a default if that's defined
This works well in most cases, except for plugins fields being maps. For such fields, this simple check may not be enough since the field may be composed of several sub-fields possibly having their own default values. This means that moving onto the next field when the current map field is set may results into its inner sub-fields not being set with default values.
In decK, where this function is heavily used, this issue results in misleading deployment diffs.
This commit expands the check logic to also …

fix: correctly ingest entity defaults with maps values

---

.github/workflows/integration-test-enterprise.yaml

[Pre-flight](https://github.com/Kong/go-kong/pull/245#pullrequestreview-1210533100) version of #245.
This PR actually runs the tests, since it's local.
https://github.com/Kong/go-kong/pull/246 is from a fork, and does not.
This does explicitly skip `test-enterprise-passed`. We don't have this currently required, but if we do I'm not sure if there's a way to make it pass like the skipped steps.

chore: add pre-flight license check

---

.github/workflows/golangci-lint.yml
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml

This PR will make it so that we use 1 version of Go in CI, specifically the one from `go.mod`.
Ref: https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file

ci: use one go version on CI

---

.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml

To avoid failures like: https://github.com/Kong/go-kong/actions/runs/3705219253/jobs/6278842598#step:7:36
> [2022-12-15T14:53:55.655Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
use codecov's token during upload.

fix: add codecov token to avoid failures in upload process

---

CHANGELOG.md
kong/client.go
kong/config_service.go
kong/config_service_test.go
kong/request.go
kong/request_test.go
kong/test_utils.go

This PR adds possibility to send declarative configs to Kong [via `/config`](https://docs.konghq.com/gateway/latest/admin-api/#reload-declarative-configuration).
It also makes `Client.NewRequestRaw()` more "flexible" ( I guess? ) by checking the type of the accepted argument and calls `json.Marshal()` only when the provided argument is not `string`, `[]byte` or `io.Reader`.
---
Unfortunately we cannot accept proper types as parameters because [deck already imports go-kong](https://github.com/Kong/deck/blob/be0eaa0835c8ca90fb5944481defe6ac534a41be/go.mod#L22) so using e.g. [`KongRawState`](https://github.com/Kong/deck/blob/0df3f51cb93669eaf661051f292eb176923c0e88/utils/types.go#L27-L56) or [`file.Content`](https://github.com/Kong/deck/blob/0df3f51cb93669eaf661051f292eb176923c0e88/file/types …

feat: add Client.ReloadDeclarativeConfig()

---

kong/client_test.go

Remove `TestRunWhenEnterprise` since all it's doing is checking wether the version information retrieved via `client.Root()` is an enterprise version when `RunWhenEnterprise()` check passes which uses the same methods underneath to check whether the used version of Kong Gateway is indeed enterprise 🤯 
Fixes #212

test: remove TestRunWhenEnterprise

---

CHANGELOG.md
kong/plugin_service_test.go
kong/utils.go

Kong plugin schemas support different type of fields, including maps. Moreover, these can either be arbitrary maps, or maps with their own subschema.
go-kong already supports well the second case, but it falls short with arbitrary maps. An example of arbitrary map field is the `custom_fields_by_lua` from the `http-log` plugin, which is defined as follows:
```
{
"custom_fields_by_lua": {
"keys": {
"len_min": 1,
"type": "string"
},
"type": "map",
"values": {
"len_min": 1,
"type": "string"
}
}
}
```
This commit makes sure that go-kong is able to correctly handle such schemas as well.

fix: correctly fill plugins with arbitrary map fields

---

CHANGELOG.md
kong/error.go
kong/error_test.go
kong/response_test.go

This adds raw error response bodies to APIErrors. This is a breaking change, as it modifies the public `kong.NewAPIError()` function signature, adding a new `raw []byte` parameter for the raw body.
go-kong does not provide universal coverage of all Kong endpoints, and does not have rich error handling for all endpoints it does cover. Currently, go-kong reads the body of any admin API error response (consuming it, so nothing downstream can read it) and extracts the `message` field for inclusion in the APIError it returns. It is not possible to perform further parsing on error bodies if desired.
Adding the raw response allows downstream clients to handle their own error parsing, primarily for ad-hoc requests where downstream builds its own requests and runs it via a go-kong client. I think …

feat: include raw response bodies in APIErrors

---

.ci/setup_kong.sh
.github/workflows/integration-test-nightly.yaml
.github/workflows/integration-test.yaml
Makefile
kong/acl_service_test.go
kong/basic_auth_service_test.go
kong/ca_certificate_service_test.go
kong/certificate_service_test.go
kong/client.go
kong/client_test.go
kong/consumer_service_test.go
kong/hmac_auth_service_test.go
kong/jwt_auth_service_test.go
kong/key_auth_service_test.go
kong/key_service_test.go
kong/keyset_service_test.go
kong/oauth2_auth_service_test.go
kong/plugin_service_test.go
kong/route_service_test.go
kong/service_service_test.go
kong/sni_service_test.go
kong/target_service_test.go
kong/test_utils.go
kong/upstream_node_health_service_test.go
kong/upstream_service_test.go

This also bumps default kong image to 3.1.1 and makes some minor refactor in test skipping conditionals (marking `t.Helper()` to prevent logging helper line numbers but to print corresponding test line numbers)

ci: add testing against dbless

---

.github/workflows/integration-test-enterprise-nightly.yaml
.github/workflows/integration-test-enterprise.yaml

To prevent bypassing branch protection rules, don't run enterprise nightly tests just as we do regular enterprise tests already.

fix(ci): don't run enterprise nightly tests for outside contributors

---

README.md

This commit is updating the Compatibily section within the README file, making sure it matches the current status.
The `1.x` reference is dropped, since we don't even test go-kong against 1.x releases anymore, and a `3.x` reference is added.

docs: update compatibility section of README

---

CHANGELOG.md
kong/client.go

Omit the response body from config push error strings. ReloadDeclarativeRawConfig already returns the body separately, so formatting it into the error is unnecessary.
Currently, formatting the body into the error string results in KIC logs like:
```
ERRO[0039] could not update kong admin                   error="performing update for http://172.22.0.102:8001 failed: failed posting new config to /config: got status code 400 and body {\"code\":14,\"fields\":{\"services\":[{\"path\":\"value must be null\",\"@entity\":[\"failed conditional validation given value of field 'protocol'\"]}]},\"name\":\"invalid declarative configuration\",\"flattened_errors\":[{\"entity_name\":\"50a88f89-b578-4c77-a3fe-5371884f306c.httpbin.httpbin..80\",\"entity_tags\":[\"k8s-name:httpbin\",\"k8s-namespace:50a88f89 …
```

fix: omit response body from config push error and release 0.38.1

---

.github/workflows/golangci-lint.yml

After `actions/setup-go@v4` introduces automatic go caching we can do away with golangci-lint action's cache.
Exemplar failures: https://github.com/Kong/go-kong/actions/runs/4436756271/jobs/7785584917#step:4:23

chore(ci): skip caching in golangci/golangci-lint-action

---

.ci/_common.sh
.ci/setup_kong.sh
.ci/setup_kong_ee.sh

Currently setup script are very fragile and susceptible to the state of the environment.
For instance when docker network used for tests already exists then user is greeted with 
```
Error response from daemon: network with name kong-test already exists
```
When that is sorted `./.ci/setup_kong_ee.sh` prints out:
```
d49438e56decc80a8ec362b515731cd551ee1536571eef7fb55e59f6f3ade158
./.ci/setup_kong_ee.sh: line 37: conditional binary operator expected
```
This PR aims to fix that and to extract some small utility functions to `./ci/_common.sh` which is then sourced in `setup_kong_ee.sh` and `setup_kong.sh`

ci: fix setup kong scripts

---

kong/utils.go
kong/utils_test.go

Add handling for type "record" nested under type "array". 
Currently there is no handling for subconfig of type array, therefore defaults/nil values are not set when there are missing fields in array of records
This fixes the issue by recursively calling the same function for all the records in the array.
Added test for the same
Fixes: #301

fix: fill config defaults for array of records

---

.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml

Include 3.2.2 open source image and bump EE images with those that were released recently.

chore: bump kong versions in integration tests strategy matrix

---

go.mod

Retract v0.30.1 to prevent anyone depending on it.
ref: https://go.dev/ref/mod#go-mod-file-retract

chore: retract v0.39.1

---

kong/plugin_service_test.go

Separate the plugin arbitrary map default test from the main default test. The new test only checks the arbitrary map field.
Changes to the test plugin in upstream Kong break the blanket diff used in the main test, and would require a version split without testing only the relevant field.
The issue appeared in https://github.com/Kong/go-kong/actions/runs/4718806033/jobs/8369120871?pr=315
```
=== RUN   TestFillPluginDefaults/nested_config_with_arbitrary_map_field
plugin_service_test.go:706:   &kong.Plugin{
... // 5 identical fields
Service:  nil,
Consumer: nil,
Config: kong.Configuration{
"content_type":         string("application/json"),
"custom_fields_by_lua": map[string]any{"foo": string("bar")},
- 		"flush_timeout":        nil,
+ 		"flush_timeout":        float64(2),
"headers": …
```

chore(tests) split out plugin map test

---

CHANGELOG.md
kong/ids.go
kong/ids_test.go

Adds `FillID` methods for Service, Route, and Consumer entities to allow setting deterministic IDs for entities based on their unique properties.
For now, it is only implemented for Service, Route and Consumer as that's what's needed on Kubernetes Ingress Controller side to generate stable IDs for analytics in Konnect.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3906.

feat: add FillID method for Service, Route and Consumer

---

kong/plugin_service.go
kong/plugin_service_test.go

Should fix #324.
The `GET /plugins/schema/<pluginName>` endpoint that `GetSchema` was using has been recently removed https://github.com/Kong/kong/pull/10846.

tests: use GetFullSchema instead of deprecated GetSchema

---

CHANGELOG.md
kong/client.go
kong/error.go
kong/response.go
kong/response_test.go

Adds `Details` and `SetDetails` methods to `APIError` struct to allow propagating status code specific information, e.g. content of the `Retry-After` header for 429 which is also added in this PR.
It's needed in order to gracefully handle rate limiting on Kong Ingress Controller side.

feat: add Details to APIError and propagate Details for 429

---

.golangci.yml

See https://github.com/Kong/go-kong/actions/runs/5171929210/jobs/9315785132?pr=333 for example problem.
golangci-lint version 1.53 upgraded the depguard linter from v1 to v2. AFAICT v1's behavior with no configuration to allow all packages, whereas v2 apparently denies everything but the standard library and local files (unclear--I'm not sure where the defaults actually live and the depguard change logs do not mention this, but it appears to be the case from my testing). https://github.com/golangci/golangci-lint/pull/3795#issuecomment-1576920783 agrees but doesn't indicate the cause of the default change.
The presence of a denylist will instead deny _only_ those packages and allow all others. The tests I can find in golangci-lint appear to all use a denylist and may be missing the default …

chore: add depguard config for linter

---

kong/utils.go
kong/utils_test.go

Fixes #334 
Adds a check for required while recusrively filling defaults for subconfig of type record.
Current behaviour of KIC is out of sync from Kong Lua implementation.
There are some field "required" checks in Lua code: [here](https://github.com/Kong/kong/blob/2a3e9193c37a8df3eb3edae6728fa84b4bfed820/kong/db/schema/init.lua#L1020) and [here](https://github.com/Kong/kong/blob/2a3e9193c37a8df3eb3edae6728fa84b4bfed820/kong/db/schema/init.lua#L1538)
These checks are missing form go code

fix: fill defaults for non-required field of type "record"

---

CHANGELOG.md
kong/utils.go
kong/utils_test.go

To avoid panic errors, in case of a wrong `[]` being set in the config for a record field, let's treat it as a nil and create the proper object map.
Can be reproduced with a deck sync:
```
_format_version: "3.0"
plugins:
- config:
storage_config:
redis: []
enabled: true
name: acme

fix: handle empty array as nil when filling record defaults

---

kong/admin_service_test.go
kong/mtls_auth_service_test.go
kong/workspace_service_test.go
third_party/golangci-lint.go
tools/tools.go

**What this PR does / why we need it**:
Since Go 1.18 the new directive `//go:build` is now preferred and the toolchain will actively remove old directives; as mentioned in Go 1.18 release notes:
> In Go 1.18, go fix now removes the now-obsolete // +build lines in modules declaring go 1.18 or later in their go.mod files.
KIC  specifies in `go.mod` Go version `1.20`.
**Which issue this PR fixes**:
It's part of the https://github.com/Kong/team-k8s/issues/286
**Special notes for your reviewer**:
Files generated by `controller-gen`:
- `kong/zz_generated.deepcopy.go`
still include obsolete build tag. Issue has been created https://github.com/kubernetes-sigs/controller-tools/issues/826

chore(build): get rid of obsolete Go build tags

---

CHANGELOG.md
kong/client.go
kong/client_test.go

This PR introduces a new helper to retrieve Kong's current config. The return value is an interface, and needs to be correctly parsed by the caller.
Fixes #353 
This endpoint is only available when Kong is configured to not use a database, therefore it is tested only with Kong dbless.

feat: config helper

---

CHANGELOG.md
kong/consumer_group.go
kong/ids.go
kong/ids_test.go

Adds FillID methods for Consumer Group entities to allow setting deterministic IDs for entities based on their unique properties.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/4358 (prerequisite)

feat: add FillID() method for Consumer Group

---

kong/client_test.go

Replace a banned module with the preferred version.
For some reason this banned module was in use but showed up as indirect. Somehow https://github.com/Kong/go-kong/pull/359 made it not indirect.
```
run golangci-lint
Running [/home/runner/golangci-lint-1.53.3-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
Error: import of package `gopkg.in/yaml.v2` is blocked because the module is in the blocked modules list. `sigs.k8s.io/yaml` is a recommended module. (gomodguard)
Error: issues found
Ran golangci-lint in 17695ms
```

chore(deps) replace yaml lib

---

.ci/setup_kong.sh
.ci/setup_kong_ee.sh
.github/workflows/integration-test-enterprise-nightly.yaml
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test-nightly.yaml
.github/workflows/integration-test.yaml
CHANGELOG.md
kong/client_test.go
kong/plugin_service_test.go
kong/route_service.go
kong/route_service_test.go
kong/service_service_test.go
kong/test_utils.go
kong/utils_test.go
kong/vault_service_test.go

**What this PR does / why we need it:**
Gateway offers API for validating routes - `/schemas/routes/validate`. This PR extends `RouteService` with the method `Validate` (that calls aforementioned endpoint) and prepares the release of the new version `v0.47.0`.
**Which issue this PR fixes:**
Prerequisite to implement https://github.com/Kong/kubernetes-ingress-controller/issues/4557.
**Special notes for your reviewer:**
Hence this method will be used to validate expressions routes, extend tests with this configuration, and introduce a helper to skip tests when it is not applicable (also a small refactor to avoid unnecessary duplication). Extend the tests matrix with such a configuration, tests run quickly, but on the other hand, need a lot of runners - using `exclude` in workflow helps a …

feat: add method Validate for RouteService

---

CHANGELOG.md
kong/utils.go
kong/utils_test.go

This commit fixes a bug preventing users to set fields to emtpy arrays when a default for those fields exist. For example, imagine we have an `openid-connect` plugin configured via the UI having the `login_tokens` set to an empty array (note: this field has a default value of `["id_token"]`:
```
$ http :8001/plugins/$id | jq .config.login_tokens
[]
```
If we do a `deck dump`, the configuration will be reflected into a local state file:
```
$ deck dump --yes
$ cat kong.yaml | grep login_tokens
login_tokens: []
```
But, if we now run `deck diff` we see that decK will detect a difference because of the `login_tokens` field's default value:
```
$ deck diff
updating plugin openid-connect (global)  {
"config": {
"anonymous": null,
...
...
"login_redirect_mode": "fragment",
"login_redirect_uri": …
```

fix: don't overwrite fields set to empty arrays when default exists

---

CHANGELOG.md
kong/route.go
kong/route_service_test.go
kong/test_utils.go
kong/utils.go
kong/zz_generated.deepcopy.go

Route's priority in expression routes should be of type `uint64` instead of int.
---
There's a related (linked in the comment) issue for Gateway which returns integers in scientific notation: https://konghq.atlassian.net/browse/FTI-5515. When that's solved the commented test case should be uncommented.
---
Also update the changelog to release 0.48.0.

fix: update Route's priority type to uint64

---

.github/workflows/integration-test-enterprise-nightly.yaml
.github/workflows/integration-test-enterprise.yaml

This change is required to accommodate the forthcoming work in https://github.com/Kong/kong-license/pull/25
That work will change kong-license such that the license is sourced directly from 1Password, rather than it being sourced from Pulp using credentials from 1Password (as is the case today). Meaning that workflows needing to run Kong/kong-license's will require 1P credentials instead of the Pulp password.
This work is a necessary step in the deprecation of Pulp aka [KAG-2247](https://konghq.atlassian.net/browse/KAG-2247) / [KAG-3254](https://konghq.atlassian.net/browse/KAG-3254).
Leaving the Pulp password for now so that https://github.com/Kong/kong-license/pull/25 can be merged *after* this PR.
[KAG-2247]: https://konghq.atlassian.net/browse/KAG-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

chore(gha): preemptively add 1p creds

---

CHANGELOG.md
kong/vault_service.go

Add `Validate()` method to call `/schemas/vaults/validate` to validate vaults.

add validate method in vault service

---

CHANGELOG.md
kong/ids.go
kong/ids_test.go
kong/vault.go

Add `FillID` method for `Vault`. Fixes #390.

feat: add FillID() method for vaults

---

CHANGELOG.md
kong/ids.go
kong/ids_test.go

Add `workspace` parameter in `FillID` methods of supporting entities to avoid ID conflict on entities in different namespaces with the same "key". fixes #394.

add workspace param in FillID methods

---

CHANGELOG.md
kong/response.go
kong/response_test.go

Extract `details` field from response if error happens in calling admin API on Konnect to do CRUD of entities. fixes #398.

extract details from response

---

CHANGELOG.md

We forgot to add these links for the past 3 releases.

chore: add missing releases' compare links in changelog

---

kong/consumer_group.go
kong/zz_generated.deepcopy.go

This commit is adding a new `ConfigSource` field into the `ConsumerGroupPlugin` struct. This is not a field that should be used for online operation, but it's needed by the the `go-database-reconciler` to allow decK to work with plugins config deduplication with Consumer Groups as well.
Ref: https://docs.konghq.com/deck/latest/guides/deduplicate-plugin-configuration/

feat: add ConfigSource field into ConsumerGroupPlugin

---

.ci/setup_kong.sh
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml
kong/client_test.go
kong/developer_role_service_test.go
kong/developer_service_test.go
kong/plugin_service_test.go

Update CI with most recent versions of Kong.
This also changes the 
- Kong version requirements in https://github.com/Kong/go-kong/blob/da7d97002cc92a764a80f13d5bcfe134a2924bac/kong/developer_role_service_test.go and https://github.com/Kong/go-kong/blob/da7d97002cc92a764a80f13d5bcfe134a2924bac/kong/developer_service_test.go from <3.7 to <3.5 as developer portal has been removed in that version.
- Kong version requirements in https://github.com/Kong/go-kong/blob/67f71c409919db806a414dcb9b2e56872084b4ca/kong/plugin_service_test.go#L549-L737 in several subtests. The reason for this change is that `realm` plugin config field for `basic-auth` has been introduced in 3.6 and not in 3.7. Re: https://docs.konghq.com/hub/kong-inc/basic-auth/changelog/#kong-gateway-36x

chore(ci): update Kong versions in CI

---

CHANGELOG.md
kong/utils.go
kong/utils_test.go

Before this change, during the process of filling default configuration values, if a record existed in the schema with a structure similar to the following:
```
{
"default": {
"some_field": "record_level_default"
},
"fields": [
{
"some_field": {
"type": "string",
"default": "field_level_default"
}
}
]
}
```
the value `record_level_default` would be ignored and the field set to the `field_level_default` value. Similarly, in case of no field-level default, the field would be set to `null`.
This commit modifies the utils/fillConfigRecord logic to assign fields with record-level default values when available.
Example of default configuration values that were previously ignored: https://github.com/Kong/kong/blob/8fe14097a17cf904676672fc8cdaabe5e02e4a2d/kong/plugins/opentelemetry/schema.lua#L49 …

fix(utils): support record-level default schema values

---

kong/test_utils.go

I observed panics couple of times in tests. Validating type assertion before proceeding further should prevent this panic.

chore: validate type assertion to prevent panic

---

kong/route.go
kong/route_service_test.go

Since Kong gateway will limit the `priority` in routes to be less than `2^46` (in `[0,2^46-1]`) , the `priority`of route used in tests should be updated to be in the interval.

test: update priority in route to `2^46 - 1`

---

CHANGELOG.md
kong/schema_service.go
kong/schema_service_test.go

Add `SchemaService.Validate` to call `POST /schemas/{entity type}/validate` to validate arbitrary type of Kong entity. Required for validating custom entities against Kong gateway in KIC https://github.com/Kong/kubernetes-ingress-controller/issues/5975.

feat: add SchemaService.Validate to validate arbitrary entity

---

CHANGELOG.md
kong/client.go
kong/client_test.go

Makes `ReloadDeclarativeRawConfig` return an `APIError` when the status code is <200 or >=400.
KIC needs to inspect the HTTP response status code when invoking `ReloadDeclarativeRawConfig` to decide whether it's a recoverable issue (4xx) or not (5xx).
Required for https://github.com/Kong/kubernetes-ingress-controller/pull/6237.

feat: return APIError from ReloadDeclarativeRawConfig

---

CHANGELOG.md
kong/client.go
kong/client_test.go

Simplify `ReloadDeclarativeRawConfig` signature so it complies with Go standards.

feat: drop resp body from ReloadDeclarativeRawConfig signature

---

kong/utils.go
kong/utils_test.go

As of now, deprecated fields are renamed to shorthand_fields in all schemas, as per the conventions. Till now, we do not fill any values for these fields while attempting to fill config records for plugins. This creates a visualisation problem in decK. Everytime, a deck diff or deck sync command is issued, it shows that the deprecated field values are changed and need to be updated, thus running an unnecessary update process each time and also confusing end users.
Check https://github.com/Kong/deck/issues/1251 for details.
This fix attempts to fill defaults for the shorthand_fields, retaining their values, if passed. Also, since shorthand_fields take priority over normal/nested fields in the gateway, if any changes are detected in shorthand_fields, it is backfilled to nested fields as …

fix: fill config values and defaults in shorthand fields

---

kong/utils.go
kong/utils_test.go

follow up of: https://github.com/Kong/go-kong/pull/466, prevent unset records to be filled with empty tables: {}
KAG-5380

fix(utils): do not fill empty records

---

kong/utils.go

In schemas, shorthand_fields that are deprecated
will use "replaced_with" going forward to convey the new fields that would be used in place of the old ones. Earlier, "translate_backwards" was used for the same.
This change ensures that both of the above mentioned fields can be used to find the new path that leads to the new values for comparison purposes. This will help tools like deck to show diff between syncs.
Fixes [deck #1440](https://github.com/Kong/deck/issues/1404)
Corresponding PR: https://github.com/Kong/kong/pull/13768

fix: use replaced_with to check for deprecated fields

---

kong/consumer_group_service.go
kong/consumer_group_test.go

Gateways before 3.9 return a list of consumers
along with consumer_group information, when
performing a GET call on a specific consumer_group. This can become slow in case a consumer_group has
a lots of consumers. A separate endpoint and relevant constructs already exist to fetch consumers for a
particular group. Thus, we are trying to not list
consumers while fetching a consumer_group by passing a query parameter in the API call. Gateway 3.9 supports this.
This will make decK faster for cases where a consumer- group holds thousands of consumers.
For: https://github.com/Kong/deck/issues/1457

feat: do not list consumers in a GET Consumer Group call

---

.github/workflows/golangci-lint.yml
.github/workflows/integration-test-enterprise-nightly.yaml
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test-nightly.yaml
.github/workflows/integration-test.yaml

Pin all imported 3rd party github actions by hashes.

Chore(ci): Pin 3rd party actions by hashes

---

CHANGELOG.md
kong/consumer_group_service.go
kong/consumer_group_test.go

Reverted the existing `Get` method to keep listing consumers and added a new one that uses the query
parameter `list_consumers=false` to skip listing
consumers for performance reasons.
This is done so as to fix dump errors coming in
deck when using gw 3.9+ where consumer-groups
do not show the associated consumers. We will
push the performant option behind a flag.
For: https://github.com/Kong/deck/issues/1483

fix: added new method to fetch a consumer-group without consumers.

---

.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml

This PR adds 3.9 and removes unsupported 2.x versions from the test matrix.

chore(ci): add 3.9 to test matrix

---

.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test.yaml
Makefile

This introduces a dynamic test matrix for Kong versions.
Ideally this would be done with a workflow on schedule so that no unexpected failures happen in unrelated CI but 1 thing at a time.
Part of #519

ci: dynamic kong version matrix

---

kong/acl_service.go
kong/acl_service_test.go
kong/basic_auth_service.go
kong/basic_auth_service_test.go
kong/credentials_service.go
kong/hmac_auth_service.go
kong/hmac_auth_service_test.go
kong/jwt_auth_service.go
kong/jwt_auth_service_test.go
kong/key_auth_service.go
kong/key_auth_service_test.go
kong/oauth2_auth_service.go
kong/oauth2_auth_service_test.go

These changes are being made to support the fix for https://github.com/Kong/deck/issues/1543.
Changes made:
- GetByID function added to the credential service, and each credential
- Tests
https://kongstrong.slack.com/archives/CQK8J4VN3/p1741703868872269
Skipped mtls auth - gateway does not seem to support Get By ID endpoint.

Add GetByID interface for credentials - such as ACL, basic auth etc

---

.ci/setup_kong.sh
.ci/setup_kong_ee.sh
kong/filter_chain_service_test.go
kong/plugin_service_test.go
kong/route_service_test.go
kong/service_service_test.go

`kong/kong-gateway-internal` nightlies removed support for WASM in of the shelf builds so remove it from default CI config.

fix(ci): fix nightly tests

---

kong/filter_chain_service_test.go
kong/plugin_service_test.go
kong/route_service_test.go
kong/service_service_test.go
kong/test_utils.go

Wasm has been removed from Kong master/nightly images. Normally a version range would do the trick to target and skip these tests (since we can assume versions >3.10 should therefore be skipped), but as of this writing the version metadata has not been updated in master.
I still updated the version range, but to catch the nightly case I added an explicit configuration check.
fixes: #531

tests: skip wasm-related tests when wasm is not enabled

---

kong/test_utils.go
kong/utils_test.go

Kong Enterprise added `throttling` field to the `rate-limiting-advanced` plugin and assigned default values for it: https://github.com/Kong/kong-ee/pull/12243
The PR sets the default value of `config.throttling` field of RLA plugin if the Kong version supports (>= 3.11).

Set default value of `config.throttling` field of RLA plugin in integration tests when Kong version >= 3.11

---

CHANGELOG.md
kong/ids.go
kong/ids_test.go

Implement `FillID` method for Plugin for https://github.com/Kong/kubernetes-ingress-controller/issues/7394. 
Because GDR regards plugin with the same name, service, route, consumer, and consumer group as the same plugin, the method for generating ID takes them into account.

feat: Implement FillID method for plugins

---

kong/consumer_group.go
kong/consumer_group_consumer_service.go

This PR fixes the request body sent while creating a consumer group consumer - we were sending an array of UUIDs in `consumer` field while according to API spec we should be sending a single UUID.
Fixes https://konghq.atlassian.net/browse/APIOPS-121
API spec for reference: https://docs.konghq.com/gateway/api/admin-ee/latest/#/operations/post-consumer_groups-group_name_or_id-consumers_with_workspace
Haven't added additional tests since there is already one - https://github.com/Kong/go-kong/blob/main/kong/consumer_group_consumer_test.go#L36
I have tested this on deck through integration and manual tests.

fix: consumer group consumer create request body to align with API spec

---

.github/workflows/integration-test.yaml
Makefile
kong/rbac_user_service.go
kong/rbac_user_service_test.go
kong/upstream.go
kong/utils_test.go
kong/workspace_service_test.go
kong/zz_generated.deepcopy.go

Kong Gateway upstream has added two new fields to support session stickiness in version 3.11 and later. This PR updates the Upstream entities in go-kong to match the Gateway upstream entity.

feat(upstream): add StickySessionsCookie and StickySessionsCookiePath

---

.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yml
.github/workflows/integration-test-enterprise-nightly.yaml
.github/workflows/integration-test-enterprise.yaml
.github/workflows/integration-test-nightly.yaml
.github/workflows/integration-test.yaml

This allows the PRs that run in fork context to fall back to this introduced value (10).

ci: use a default workflow timeout fallback value

---

kong/target.go
kong/target_service_test.go
kong/utils_test.go
kong/zz_generated.deepcopy.go

Added in Gateway 3.12
You can set `failover: true` to indicate that a Target should be used as a failover (backup) Target in case the other, regular targets (`failover: false`) associated with an Upstream are unhealthy. The failover Target is only used when all regular Targets are unhealthy. You can set one or multiple failover Targets for an Upstream.

Add Failover parameter to Target
